spring:
  application:
    name: MindCash
  datasource:
    url: jdbc:mysql://localhost:3306/mindcash-mysql
    username: dev
    password: dev
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    open-in-view: true
  thymeleaf:
    cache: false
  web:
    resources:
      static-locations: classpath:/static/
server:
  port: 8088
logging:
  file:
    path: ./var/log
  level:
    org.flywaydb: DEBUG
    org.springframework.boot.autoconfigure.flyway: DEBUG